Duke-GCB/calrissian

.circleci/config.yml, calrissian/context.py, calrissian/job.py, calrissian/k8s.py, calrissian/main.py, calrissian/tool.py, requirements.txt, run.sh, test.sh, tests/test_context.py, tests/test_executor.py, tests/test_job.py, tests/test_k8s.py, tests/test_tool.py, tests/test_version.py
- Updates code to use absolute imports everywhere (this codebase is python 3 only)
- Refactors some functionality in volume builder for easier testing and future cleanup
- Simplifies k8s API client to only watch one job per instance
- Updates run.sh script to run main with `-m`
Fixes #3
=> Implement unit tests and configure for CircleCI

.gitignore, test-coverage.sh
Script to run tests under [coverage](https://coverage.readthedocs.io/en/v4.5.x/) and report code coverage in calrissian package
=> Add script to run tests with coverage

README.md, openshift/BuildConfig.yaml, openshift/CalrissianJob-fail-wf.yaml, openshift/CalrissianJob-revsort.yaml, openshift/StageInputDataJob.yaml
As documented in https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#using-is-with-k8s, the image lookup policy can be set to allow Kubernetes resources (like Jobs) to lookup image stream images.
This change enables that in BuildConfig.yaml and uses it in the jobs.
=> Update ImageStream to let jobs use local image name

calrissian/job.py, calrissian/tool.py, input-data/revsort-array.cwl, input-data/revsort-single-no-docker.cwl, input-data/revtool-no-docker.cwl, input-data/sorttool-no-docker.cwl, openshift/CalrissianJob-revsort-single-default-container.yaml, openshift/CalrissianJob-revsort-single.yaml, tests/test_job.py, tests/test_tool.py
- CalrissianCommandLineTool now injects a DockerRequirement with the `--default-container` docker image if the tool has no DockerRequirement. This mirrors behavior in cwltool's base CommandLineTool and is explained in comments.
- CalrissianCommandLineJob now checks for unsupported `DockerRequirement` features and fails if they cannot be met
-  Adds version of revsort single file workflow that does not include a `DockerRequirement` for testing these features. See sample job `CalrissianJob-revsort-single-default-container.yaml` that calls it and specifies `--default-container`
Fixes #7
=> Injects DockerRequirement into tool if it is not present

calrissian/executor.py, calrissian/job.py, calrissian/k8s.py, tests/test_job.py, tests/test_k8s.py
Updates from attempting to run [exomeseq-gatk4-preprocessing.cwl](https://github.com/Duke-GCB/bespin-cwl/blob/master/workflows/exomeseq-gatk4-preprocessing.cwl)
- Makes pod names unique
- Adds option to skip deleting pods
- Adjusts some logging, reports usage before executor methods
- Quotes arguments in container args array if needed
- Fixes translation of CWL ResourceRequirements to k8s resources
=> Changes based on bringing a real workflow online

.dockerignore, Dockerfile, calrissian/version.py, openshift/BuildConfig.yaml, openshift/CalrissianJob-fail-wf.yaml, openshift/CalrissianJob-revsort-single-default-container.yaml, openshift/CalrissianJob-revsort-single.yaml, openshift/CalrissianJob-revsort.yaml, requirements.txt, setup.py, tests/test_version.py
- Adds setup.py with packaging information (as initial version 0.1.0). When installed, can be run as `calrissian` instead of `python -m ...`
- Updates `version.py` to report the version of calrissian and cwltool
- Adds Dockerfile to install on top of `python:3.6` (includes nodejs)
- Rewrites openshift BuildConfig to use the `Dockerfile` instead of a source-to-image build.
- Updates example job to use the `calrissian` CLI script as `command` and arguments as `args`.
Fixes #40
=> Setuptools installer, Dockerfile, and updated BuildConfig

calrissian/main.py, tests/test_main.py
Allows user to run `calrissian --version` without requiring `--max-ram` and `--max-cores`
Fixes #43
=> Print out version and exit when running `calrissian --version`

calrissian/context.py, calrissian/job.py, calrissian/main.py, tests/test_context.py, tests/test_job.py, tests/test_main.py
Add labels to submitted Pods using --pod-labels <yaml_file>
- Adds CalrissianRuntimeContext subclass with a pod_labels attribute
- CalrissianCommandLineJob reads the YAML (or JSON) file of labels and provides a dictionary to KubernetesPodBuilder
- KubernetesPodBuilder takes a dictionary of labels in its constructor, to provide as the pod's metadata.labels (ensuring conversion to string)
Fixes #38
=> Option to apply labels to submitted pods

Dockerfile
Creates `$HOME` at `/home/calrissian`, owned and writable by group `0`.
This follows the openshift practices for [Supporting Arbitrary User IDs](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines)
=> Set HOME and create default user in Dockerfile

README.md, openshift/VolumeClaims.yaml
Example volume claims in `openshift/VolumeClaims.yaml` had a namespace specified. This is not necessary, and by removing it, the examples can more easily be run on other namespaces, and we don't need to adjust the examples in `openshift/` for templating with scripts or helm.
Closes #18
=> Remove namespace from VolumeClaims

calrissian/main.py, openshift/CalrissianJob-revsort.yaml, tests/test_main.py
Adds optional command-line arguments to specify files for writing standard output and standard error
- If specified, these files are written by piping through `tee`, meaning that stdout/stderr still are written to the kubernetes pod logs, but also to the named files.
- This feature allows other tools that run calrissian in kubernetes (e.g. lando) to declare what files to write to, without a shell and without silencing job logs
Baseline functionality for #17
=> Adds --stdout and --stderr args for writing output to files

README.md, calrissian/k8s.py, tests/test_k8s.py, tests/test_report.py
- After submitting a pod, follows stream of logs using `read_namespaced_pod_log()`
- Sends log lines to `log.debug()`, prefixed with the name of the pod in square brackets
- Also fixes a couple of stray test bugs found along the way
Fixes #17
=> Sends CWL tool logging to calrissian debug / stderr

calrissian/job.py, calrissian/report.py, tests/test_job.py, tests/test_report.py
- Reworks `CalrissianCommandLineJob.finish()` to add the size of files written and the job's name to the report entry
- Updates `CalrissianCommandLineJob.finish()` to call back in a thread safe manner and clean-up tmpdir/stagedir according to cwltool's implementation
- Updates reporting to include disk megabytes written and name per task, as well as a total megabytes written by all steps
- Refines behavior in reporting to eliminate reporting exceptions from incomplete jobs  (#58)
Fixes #53 
Fixes #58
=> Adds storage usage and job name to each step in usage report

calrissian/job.py, openshift/CalrissianJob-fail-wf.yaml, openshift/CalrissianJob-revsort-single-default-container.yaml, openshift/CalrissianJob-revsort-single.yaml, openshift/CalrissianJob-revsort.yaml, openshift/VolumeClaims.yaml, tests/test_job.py
- Updates KubernetesVolumeBuilder to support a list of named emptyDir volumes
- Updates CalrissianCommandLineJob.create_kubernetes_runtime to use an emptyDir volume for '/tmp' inside the container
Upon implementation, I don't think this will conflict with any of the special cases mentioned in #30 (writable files being copied into /tmp). These files are copied on the calrissian host and mounted later (via `add_volumes()`). This change will mount the base `/tmp` as an `emptyDir` but additional direct mounts to files placed by calrissian shouldn't be impacted.
tl;dr - this is a simple fix for #30 that shouldn't break the existing special cases (that we don't use anyway)
Fixes #30
=> Use emptyDir for '/tmp' inside containers

setup.py
Requests requires a specific range of urllib3 versions, but kubernetes is less picky and installed an incompatible version. This change specifies a version of urllib3 compatible with everyone as the first required package in setup.py
=> Specify urllib3 to be a compatible version

calrissian/job.py, examples/CalrissianJob-fail-wf.yaml, examples/CalrissianJob-revsort-single-default-container.yaml, examples/CalrissianJob-revsort-single.yaml, examples/CalrissianJob-revsort.yaml, tests/test_job.py
Updates KubernetesPodVolumeInspector to check calrissian's claim volumes for read-only, and passes that state down to claim volumes specified for created pods.
Updates the revsort example to mark input data as a read-only claim volume and a read-only volume mount. Tested in OKD on hardspin.
Fixes #79
=> Include volume readOnly state when passing along volumes

calrissian/job.py, tests/test_job.py
- Checks if `job.stdout` or `job.stderr` are paths within directories
- Adds an `initContainer` to the Pod spec if these are directories, and creates them before attempting redirection inside the primary `container`
for #8
=> Adds initContainer to ensure stdout/stderr directories exist

calrissian/k8s.py, requirements.txt, setup.py, tests/test_k8s.py
Upgrades to use the latest k8s python library.
This doesn't seem to noticeably help with GKE reliability issue #96. 
May help with issue following logs #60.
=> Upgrade to latest stable kubernetes library release (10.0.1)

calrissian/k8s.py, tests/test_k8s.py
When an exception is raised in [cwlmain delete_pods/PodMonitor.cleanup will be called](https://github.com/Duke-GCB/calrissian/blob/3de52f853539d117ca2d2da423dcdd3858248d2a/calrissian/main.py#L118-L127). This removes all pods from PodMonitor's list. If there are active pods being monitored in other threads, when the pods exit podMonitor.remove will be run this results in `ValueError: list.remove(x): x not in list`. 
The change here handles this case by checking to see if the pod is still in the list before trying to remove it.
More details:  https://github.com/Duke-GCB/calrissian/issues/96#issuecomment-523453031.
_With refactoring changes coming up we may want to not merge this._
=> Fix error when PodMonitor cleanup is called before remove

README.md, calrissian/k8s.py, calrissian/retry.py, requirements.txt, setup.py, tests/test_k8s.py, tests/test_retry.py
Uses tenacity to retry API calls that may fail due to temporary unavailable k8s API
This work was intended to tolerate automated GKE cluster master upgrades (during which the API server is unavailable). While it addresses that and continues the workflow after the API server returns, the upgrade/autoscaling was causing nodes to delete running pods and terminate them prematurely.
In the interest of seeing a large workflow run, we'll not use auto-scaling on GKE for now, and revisit this later if necessary.
Fixes the `APIException`s, and `ConnectionError`s related to #96. The `Error Collecting Output` issues were occurring in my testing when a GKE node was killed and terminated pods running on it.
=> Implements simple k8s API retries

calrissian/context.py, calrissian/executor.py, calrissian/job.py, calrissian/main.py, calrissian/tool.py, requirements.txt, setup.py, tests/test_executor.py, tests/test_job.py, tests/test_main.py
This PR replaces the broken GPU support  introduced 0.14. 
It adds a CLI option --max-gpus to set the maximum number of GPU to use. 
It works as --max-ram, --max-cores but it is optional and to be used when the CWL description uses the cwltool#CUDARequirement extension
=> gpu-extension-evo: proper support for GPU

calrissian/executor.py, calrissian/job.py, tests/test_executor.py, tests/test_job.py
This PR addresses issue #144 by improving how CWL resource requirements are handled when scheduling pods
Fully supports CWL requirements: ramMin, ramMax, coresMin, and coresMax
When all four are present:
- **ramMin** and **coresMin** are applied as resource **requests**
- **ramMax** and **coresMax** are applied as resource **limits**
- All existing tests pass
- Added 2 new tests to validate the updated resource handling logic
=> fix: issue #144 - requests and limits resources on pod
